// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsglRzaZkozu7LlUdMGQ68W4h8x3HsqUE',
    appId: '1:661260991646:web:2b1dd41c1cb3db43540f8f',
    messagingSenderId: '661260991646',
    projectId: 'app-firebase-2557d',
    authDomain: 'app-firebase-2557d.firebaseapp.com',
    storageBucket: 'app-firebase-2557d.firebasestorage.app',
    measurementId: 'G-4WLHTPRJFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAekh0H1u_OIHQmuEfxZ4QkqPxg1wrITe0',
    appId: '1:661260991646:android:0ade33b4ed6a069c540f8f',
    messagingSenderId: '661260991646',
    projectId: 'app-firebase-2557d',
    storageBucket: 'app-firebase-2557d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5GwdK7FrCJAJsPAkFmwwrVZ9DdPDLRnk',
    appId: '1:661260991646:ios:0ed9a3bcaa04c3c3540f8f',
    messagingSenderId: '661260991646',
    projectId: 'app-firebase-2557d',
    storageBucket: 'app-firebase-2557d.firebasestorage.app',
    iosBundleId: 'com.example.miApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5GwdK7FrCJAJsPAkFmwwrVZ9DdPDLRnk',
    appId: '1:661260991646:ios:0ed9a3bcaa04c3c3540f8f',
    messagingSenderId: '661260991646',
    projectId: 'app-firebase-2557d',
    storageBucket: 'app-firebase-2557d.firebasestorage.app',
    iosBundleId: 'com.example.miApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsglRzaZkozu7LlUdMGQ68W4h8x3HsqUE',
    appId: '1:661260991646:web:8b23e3c0ceff0bd8540f8f',
    messagingSenderId: '661260991646',
    projectId: 'app-firebase-2557d',
    authDomain: 'app-firebase-2557d.firebaseapp.com',
    storageBucket: 'app-firebase-2557d.firebasestorage.app',
    measurementId: 'G-08RT3Y62RL',
  );

}